from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("ImageMixer")
        MainWindow.resize(1235, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.image2 = ImageView(self.centralwidget)
        self.image2.setMinimumSize(QtCore.QSize(200, 200))
        self.image2.setObjectName("image2")
        self.gridLayout_3.addWidget(self.image2, 3, 0, 1, 1)
        self.image1 = ImageView(self.centralwidget)
        self.image1.setMinimumSize(QtCore.QSize(200, 200))
        self.image1.setObjectName("image1")
        self.gridLayout_3.addWidget(self.image1, 1, 0, 1, 1)
        self.Openimage1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Openimage1.setFont(font)
        self.Openimage1.setObjectName("Openimage1")
        self.gridLayout_3.addWidget(self.Openimage1, 0, 0, 1, 1)
        self.Openimage2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Openimage2.setFont(font)
        self.Openimage2.setObjectName("Openimage2")
        self.gridLayout_3.addWidget(self.Openimage2, 2, 0, 1, 1)
        self.image2Edited = ImageView(self.centralwidget)
        self.image2Edited.setMinimumSize(QtCore.QSize(200, 200))
        self.image2Edited.setObjectName("image2Edited")
        self.gridLayout_3.addWidget(self.image2Edited, 3, 1, 1, 1)
        self.Image1Edited = ImageView(self.centralwidget)
        self.Image1Edited.setMinimumSize(QtCore.QSize(200, 200))
        self.Image1Edited.setObjectName("Image1Edited")
        self.gridLayout_3.addWidget(self.Image1Edited, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 4, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Output2 = ImageView(self.centralwidget)
        self.Output2.setMinimumSize(QtCore.QSize(200, 200))
        self.Output2.setObjectName("Output2")
        self.gridLayout_2.addWidget(self.Output2, 2, 1, 1, 1)
        self.Output1 = ImageView(self.centralwidget)
        self.Output1.setMinimumSize(QtCore.QSize(200, 200))
        self.Output1.setObjectName("Output1")
        self.gridLayout_2.addWidget(self.Output1, 2, 0, 1, 1)
        self.outpu1Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.outpu1Label.setFont(font)
        self.outpu1Label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.outpu1Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outpu1Label.setObjectName("outpu1Label")
        self.gridLayout_2.addWidget(self.outpu1Label, 1, 0, 1, 1)
        self.Output2Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Output2Label.setFont(font)
        self.Output2Label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Output2Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Output2Label.setObjectName("Output2Label")
        self.gridLayout_2.addWidget(self.Output2Label, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.slider1 = QtWidgets.QSlider(self.centralwidget)
        self.slider1.setMaximum(100)
        self.slider1.setSingleStep(10)
        self.slider1.setProperty("value", 0)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.gridLayout.addWidget(self.slider1, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.component2Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.component2Label.setFont(font)
        self.component2Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.component2Label.setObjectName("component2Label")
        self.gridLayout.addWidget(self.component2Label, 5, 0, 1, 1)
        self.S2Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.S2Label.setFont(font)
        self.S2Label.setObjectName("S2Label")
        self.gridLayout.addWidget(self.S2Label, 5, 3, 1, 1)
        self.S1Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Orbitron")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.S1Label.setFont(font)
        self.S1Label.setObjectName("S1Label")
        self.gridLayout.addWidget(self.S1Label, 1, 3, 1, 1)
        self.slider2 = QtWidgets.QSlider(self.centralwidget)
        self.slider2.setMaximum(100)
        self.slider2.setSingleStep(10)
        self.slider2.setProperty("value", 0)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")
        self.gridLayout.addWidget(self.slider2, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        # self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 0, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        # self.comboBox_6.addItem("")
        # self.comboBox_6.addItem("")
        # self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 2, 2, 1, 1)

        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        # self.comboBox_7.addItem("")
        # self.comboBox_7.addItem("")
        # self.comboBox_7.addItem("")
        self.gridLayout.addWidget(self.comboBox_7, 6, 2, 1, 1)
# #########################################################
        self.combo_select_img1 = QtWidgets.QComboBox(self.centralwidget)
        self.combo_select_img1.setEnabled(True)
        self.combo_select_img1.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_select_img1.setAcceptDrops(False)
        self.combo_select_img1.setIconSize(QtCore.QSize(20, 20))
        self.combo_select_img1.setObjectName("combo_select_img1")
        self.combo_select_img1.addItem("")
        self.combo_select_img1.addItem("")
        self.gridLayout.addWidget(self.combo_select_img1, 1, 1, 1, 1)

        self.combo_select_img2 = QtWidgets.QComboBox(self.centralwidget)
        self.combo_select_img2.setEnabled(True)
        self.combo_select_img2.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_select_img2.setAcceptDrops(False)
        self.combo_select_img2.setIconSize(QtCore.QSize(20, 20))
        self.combo_select_img2.setObjectName("combo_select_img2")
        self.combo_select_img2.addItem("")
        self.combo_select_img2.addItem("")
        self.gridLayout.addWidget(self.combo_select_img2, 5, 1, 1, 1)
# #########################################################
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1235, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFTReal1 = QtWidgets.QAction(MainWindow)
        self.actionFTReal1.setObjectName("actionFTReal1")
        self.actionFTReal2 = QtWidgets.QAction(MainWindow)
        self.actionFTReal2.setObjectName("actionFTReal2")
        self.actionFTImag1 = QtWidgets.QAction(MainWindow)
        self.actionFTImag1.setObjectName("actionFTImag1")
        self.actionFTImag2 = QtWidgets.QAction(MainWindow)
        self.actionFTImag2.setObjectName("actionFTImag2")
        self.actionFTMag1 = QtWidgets.QAction(MainWindow)
        self.actionFTMag1.setObjectName("actionFTMag1")
        self.actionFTMag2 = QtWidgets.QAction(MainWindow)
        self.actionFTMag2.setObjectName("actionFTMag2")
        self.actionFTPhase1 = QtWidgets.QAction(MainWindow)
        self.actionFTPhase1.setObjectName("actionFTPhase1")
        self.actionFTPhase2 = QtWidgets.QAction(MainWindow)
        self.actionFTPhase2.setObjectName("actionFTPhase2")
        self.actionimage1C1 = QtWidgets.QAction(MainWindow)
        self.actionimage1C1.setObjectName("actionimage1C1")
        self.actionimageC2 = QtWidgets.QAction(MainWindow)
        self.actionimageC2.setObjectName("actionimageC2")
        self.actionimage2C1 = QtWidgets.QAction(MainWindow)
        self.actionimage2C1.setObjectName("actionimage2C1")
        self.actionimage2C2 = QtWidgets.QAction(MainWindow)
        self.actionimage2C2.setObjectName("actionimage2C2")
        self.actionimage1C2 = QtWidgets.QAction(MainWindow)
        self.actionimage1C2.setObjectName("actionimage1C2")
        self.actionoutput1 = QtWidgets.QAction(MainWindow)
        self.actionoutput1.setObjectName("actionoutput1")
        self.actionoutput2 = QtWidgets.QAction(MainWindow)
        self.actionoutput2.setObjectName("actionoutput2")
        self.actionc1Mag = QtWidgets.QAction(MainWindow)
        self.actionc1Mag.setObjectName("actionc1Mag")
        self.actionc1Phase = QtWidgets.QAction(MainWindow)
        self.actionc1Phase.setObjectName("actionc1Phase")
        self.actionc1Real = QtWidgets.QAction(MainWindow)
        self.actionc1Real.setObjectName("actionc1Real")
        self.actionc1UnitMag = QtWidgets.QAction(MainWindow)
        self.actionc1UnitMag.setObjectName("actionc1UnitMag")
        self.actionc1UnitPhase = QtWidgets.QAction(MainWindow)
        self.actionc1UnitPhase.setObjectName("actionc1UnitPhase")
        self.actionc2Mag = QtWidgets.QAction(MainWindow)
        self.actionc2Mag.setObjectName("actionc2Mag")
        self.actionc2Phase = QtWidgets.QAction(MainWindow)
        self.actionc2Phase.setObjectName("actionc2Phase")
        self.actionc2Real = QtWidgets.QAction(MainWindow)
        self.actionc2Real.setObjectName("actionc2Real")
        self.actionc2Imag = QtWidgets.QAction(MainWindow)
        self.actionc2Imag.setObjectName("actionc2Imag")
        self.actionc2UnitMag = QtWidgets.QAction(MainWindow)
        self.actionc2UnitMag.setObjectName("actionc2UnitMag")
        self.actionc2UnitPhase = QtWidgets.QAction(MainWindow)
        self.actionc2UnitPhase.setObjectName("actionc2UnitPhase")
        self.actionc1Imag = QtWidgets.QAction(MainWindow)
        self.actionc1Imag.setObjectName("actionc1Imag")

        self.retranslateUi(MainWindow)
        self.slider1.valueChanged['int'].connect(self.S1Label.setNum)
        self.slider2.valueChanged['int'].connect(self.S2Label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImageMixer"))
        self.Openimage1.setText(_translate("MainWindow", "Open image1"))
        self.Openimage2.setText(_translate("MainWindow", "Open image2"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Components"))
        self.comboBox.setItemText(1, _translate("MainWindow", "FT Magnitude"))
        self.comboBox.setItemText(2, _translate("MainWindow", "FT Phase"))
        self.comboBox.setItemText(3, _translate("MainWindow", "FT Real"))
        self.comboBox.setItemText(4, _translate("MainWindow", "FT Imaginary"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Components"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "FT Magnitude"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "FT Phase"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "FT Real"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "FT Imaginary"))
        self.outpu1Label.setText(_translate("MainWindow", "OutPut1"))
        self.Output2Label.setText(_translate("MainWindow", "OutPut2"))
        self.label_2.setText(_translate("MainWindow", "    Component1"))
        self.component2Label.setText(_translate("MainWindow", "    Component2"))
        self.S2Label.setText(_translate("MainWindow", "0%"))
        self.S1Label.setText(_translate("MainWindow", "0"+"%"))
        self.label.setText(_translate("MainWindow", "            Mixer Output to:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Output1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Output 2"))
        # self.comboBox_3.setItemText(2, _translate("MainWindow", "Output 2"))
        # ###################################################
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Components"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "phase"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "imaginary"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "uniform phase"))
        
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Components"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "magnitude"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "real"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "uniform magnitude"))
        # ###################################################
        # self.comboBox_6.setItemText(0, _translate("MainWindow", "Components"))
        # self.comboBox_6.setItemText(1, _translate("MainWindow", "magnitude"))
        # self.comboBox_6.setItemText(2, _translate("MainWindow", "phase"))
        # self.comboBox_6.setItemText(3, _translate("MainWindow", "real"))
        # self.comboBox_6.setItemText(4, _translate("MainWindow", "imaginary"))
        # self.comboBox_6.setItemText(5, _translate("MainWindow", "uniform magnitude"))
        # self.comboBox_6.setItemText(6, _translate("MainWindow", "uniform phase"))
        # self.comboBox_7.setItemText(0, _translate("MainWindow", "Components"))
        # self.comboBox_7.setItemText(1, _translate("MainWindow", "magnitude"))
        # self.comboBox_7.setItemText(2, _translate("MainWindow", "phase"))
        # self.comboBox_7.setItemText(3, _translate("MainWindow", "real"))
        # self.comboBox_7.setItemText(4, _translate("MainWindow", "imaginary"))
        # self.comboBox_7.setItemText(5, _translate("MainWindow", "uniform magnitude"))
        # self.comboBox_7.setItemText(6, _translate("MainWindow", "uniform phase"))
        # ###################################################
        self.combo_select_img1.setItemText(0, _translate("MainWindow", "Image1"))
        self.combo_select_img1.setItemText(1, _translate("MainWindow", "Image2"))
        self.combo_select_img2.setItemText(0, _translate("MainWindow", "Image1"))
        self.combo_select_img2.setItemText(1, _translate("MainWindow", "Image2"))
         # ###################################################
        # self.radioButton.setText(_translate("MainWindow", "Image1"))
        # self.radioButton_2.setText(_translate("MainWindow", "Image2"))
        # self.radioButton_3.setText(_translate("MainWindow", "Image1"))
        # self.radioButton_4.setText(_translate("MainWindow", "Image2"))
        self.actionFTReal1.setText(_translate("MainWindow", "FTReal1"))
        self.actionFTReal2.setText(_translate("MainWindow", "FTReal2"))
        self.actionFTImag1.setText(_translate("MainWindow", "FTImag1"))
        self.actionFTImag2.setText(_translate("MainWindow", "FTImag2"))
        self.actionFTMag1.setText(_translate("MainWindow", "FTMag1"))
        self.actionFTMag2.setText(_translate("MainWindow", "FTMag2"))
        self.actionFTPhase1.setText(_translate("MainWindow", "FTPhase1"))
        self.actionFTPhase2.setText(_translate("MainWindow", "FTPhase2"))
        self.actionimage1C1.setText(_translate("MainWindow", "image1C1"))
        self.actionimageC2.setText(_translate("MainWindow", "image1C2"))
        self.actionimage2C1.setText(_translate("MainWindow", "image2C1"))
        self.actionimage2C2.setText(_translate("MainWindow", "image2C2"))
        self.actionimage1C2.setText(_translate("MainWindow", "image1C2"))
        self.actionoutput1.setText(_translate("MainWindow", "output1"))
        self.actionoutput2.setText(_translate("MainWindow", "output2"))
        self.actionc1Mag.setText(_translate("MainWindow", "c1Mag"))
        self.actionc1Phase.setText(_translate("MainWindow", "c1Phase"))
        self.actionc1Real.setText(_translate("MainWindow", "c1Real"))
        self.actionc1UnitMag.setText(_translate("MainWindow", "c1UnitMag"))
        self.actionc1UnitPhase.setText(_translate("MainWindow", "c1UnitPhase"))
        self.actionc2Mag.setText(_translate("MainWindow", "c2Mag"))
        self.actionc2Phase.setText(_translate("MainWindow", "c2Phase"))
        self.actionc2Real.setText(_translate("MainWindow", "c2Real"))
        self.actionc2Imag.setText(_translate("MainWindow", "c2Imag"))
        self.actionc2UnitMag.setText(_translate("MainWindow", "c2UnitMag"))
        self.actionc2UnitPhase.setText(_translate("MainWindow", "c2UnitPhase"))
        self.actionc1Imag.setText(_translate("MainWindow", "c1Imag"))
from pyqtgraph import ImageView



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())